### ISSUE TITLE
Develop the introduction to MRI reading list

### ISSUE THREAD

**Issue by KirstieJane** [WhitakerLab/WhitakerLabProjectManagement#14]
I (Kirstie) have really deep expert blindness when it comes to remembering how I learned about MRI (it was in 2007 at 8am every Wednesday morning at UBC in Vancouver!

This is a really tough request, but I'd like you to build up some useful resources for understanding how we use MRI for neuroimaging.

Some guidelines:

1. You don't need to know everything at the deepest level! There are some really great youtube videos or blog posts that will talk you through conceptually how MRI can be used to image the brain. I'd recommend starting with them before jumping into a pubmed search.

2. On the other hand you aren't the first person to have to learn how MRI works! There are probably some really useful introduction/overview papers that you can find. Try searching pubmed for `review` papers only...or follow links from the blogs and videos etc.

3. You can learn iteratively! You don't have to understand everything you read the first time through. If it's written in a way that you feel you might like to come back to, keep the link, add a little sentence about it to the reading list and keep going on your quest.

You got this!

**Comment by KirstieJane** [comment]
This website has some great videos: https://www.imaios.com/en/e-Courses/e-MRI. You need to register to watch the videos, but I don't think they sell your soul (and send you lots of spam) in exchange.

**Comment by Islast** [comment]
So far I have been finding this guide particularly useful
http://miykael.github.io/nipype-beginner-s-guide/neuroimaging.html

and here are a couple of other things
http://cds.ismrm.org/protected/11MProceedings/files/ISMRM2011-8410.pdf
[powerpoint](https://www.google.co.uk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=15&cad=rja&uact=8&ved=0ahUKEwi4-rvBy-DTAhViD8AKHeiYBMU4ChAWCD0wBA&url=https%3A%2F%2Fafni.nimh.nih.gov%2Fpub%2Fdist%2Fedu%2F2007_12_MRIanat%2FMRIanat.ppt&usg=AFQjCNGGC880S1R03BhaOioDB4LnZ5G7lQ&sig2=PBGU182ADZkMy9-1BzRqFA)

**Comment by KirstieJane** [comment]
YEAAAH Go go @miykael - He rocks 🎉

So glad you found that resource useful 😄

**Comment by KirstieJane** [comment]
@Islast - I forgot to say in our meeting on Friday that it would be really great if you could submit a very brief reading list about this to the repository. It doesn't have to be complete - I'm sure there will be many more people who want to add to it as we go along - but just the links to anything you found useful would be amazing 🙌

**Comment by KirstieJane** [comment]
Done! Closing issue!
