### ISSUE TITLE
Welcoming Ang to the Whitaker Lab

### ISSUE THREAD

**Issue by KirstieJane** [WhitakerLab/WhitakerLabProjectManagement#245]
13 March is @sprak0323's first day at the Turing.

Welcome @sprak0323!! ✨ 🎇 

The onboarding repository is here: https://github.com/WhitakerLab/Onboarding. We've gone through the information there together, but have a detailed read through yourself.

Some next steps:

- [x] Join slack (invitation sent by @KirstieJane, you should get an invite by email)
- [x] Work through the git-it tutorial: http://jlord.us/git-it
- [x] Write an introducing me blog post - the pictures from your pptx about your home town for example would be great! About 500 words would be great. It will go on the [whitakerlab website](https://whitakerlab.github.io/blog/).
  * Deadline: 27 March 😸 
- [x] Read about registered reports: https://cos.io/rr

**Comment by sprak0323** [comment]
Thanks for listing them! 😊 Could you please invite me to join slack again? 
I haven't received the email now

**Comment by KirstieJane** [comment]
I can't invite you, the Turing Slack administrators can so we just have to wait for them. It shouldn't take more than a couple of days 👾

**Comment by sprak0323** [comment]
Got it. 😺

**Comment by KirstieJane** [comment]
Amazing @sprak0323!! Well done
