### ISSUE TITLE
Kirstie TO DO list | 11 September 2019

### ISSUE THREAD

**Issue by KirstieJane** [WhitakerLab/WhitakerLabProjectManagement#302]
I'm wildly behind on all my tasks..... so I figured I'd make a master list of everything I need to do! 😱 

### Autistica Summit
- [x] Review applications, call w Lorcan
- [x] 1 page description of "what is AI"

### Autistica Citizen Science
- [ ] Go through issues & PRs? Ask @GeorgiaHCA to prioritise for me 🙏 
- [x] Create Heroku account & team & transfer ownership of [demo repo](https://github.com/alan-turing-institute/autistica-filemanagement-demo)
- [ ] Tell AH about the demo, check on license
- [x] Neurodiversity week at Turing - liaise w @GeorgiaHCA & ST

### Editing
- [x] Elife
- [x] Neuroimage

### Lab stuff
- [ ] Merge blog posts
- [ ] Write last week's blog post
- [ ] Add updates to hackmd
- [ ] Update who's who page on website
- [ ] Letter of recommendation for JL
- [x] Ticket for YH

### Turing Way
- [x] Advertise collab cafe in bulletin
- [x] Review PRs for SG

### Reproducible research drop ins
- [x] Advertise reproducible research drop in session in bulletin
- [x] Update repo

### BIDS
- [x] Review hackmds

### ABCD RR
- [ ] Edit overleaf

### Automating the crowd
- [x] Announce next two meetings - send calendar invite
- [x] Send around writings for review

### General email
- [x] Reply to BMG re: space

### Reproducible ML grant
- [x] Review & send comments

### DAS
- [x] Read response
- [x] Make new figure

### Invited Talks
- [ ] Write abstract & bio for citizen science event at british library
- [ ] Write abstract & bio for welcoming students event at Turing

**Comment by GeorgiaHCA** [comment]
Heya! For priorities for the issues and PRs - I would say the main ones are probably the September newsletter (in pull requests) - and questions for the focus groups (in issues). The other things like adding contributors and updating ethics docs are probs less urgent :)

**Comment by KirstieJane** [comment]
Thank you @GeorgiaHCA! Giving me priorities is super super helpful! If you can watch slack tomorrow and Friday I'll try to do bitty things in between talks at the conference 🤞

**Comment by GeorgiaHCA** [comment]
You're a star THANK YOU :D

**Comment by KirstieJane** [comment]
Closing - going to start a new one!
