### ISSUE TITLE
suggestions for the reading list for reproducibility and open science

### ISSUE THREAD

**Issue by awakenting** [WhitakerLab/WhitakerLabProjectManagement#42]
Hi,
for the reading list I would suggest to have a look at the "Ten simple rules" [collection](http://collections.plos.org/ten-simple-rules) from PLOS, some of them are probably very useful. I for example like this one:
[Ten simple rules for making research software more robust](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005412).
Cheers,
Andrej

**Comment by KirstieJane** [comment]
That sounds great @awakenting! Thank you!

Would you like to create a pull request to add these two to the reading list?

**Comment by awakenting** [comment]
Yes. Done.

**Comment by KirstieJane** [comment]
Closing this issue because pull request #51 is merged! THANK YOU! 💯
