### ISSUE TITLE
Apply for Mozilla Mini Grant

### ISSUE THREAD

**Issue by KirstieJane** [WhitakerLab/WhitakerLabProjectManagement#43]
Here's the blog post: https://science.mozilla.org/blog/mini-grant-cfp

Here's the application link: https://mozilla-science-lab.forms.fm/mozilla-science-mini-grant-application

Here's the draft: https://github.com/WhitakerLab/WhitakerLabProjectManagement/blob/mozilla-mini-grant/FUNDING_APPLICATIONS/MozillaScienceLabMiniGrant_June2017.md

Here's the budget: https://docs.google.com/spreadsheets/d/1YZQTX9H5Y8IYlgYY-ifcG57uYt1xVxFtZ1Tc4oUfxpI/edit?usp=sharing

**Comment by KirstieJane** [comment]
Questions for @stephwright:

* Where does the budget outline go in the google form?

**Comment by stephwright** [comment]
You can use the categories in the budget template (http://bit.ly/2riERqD) or just create your own outline and submit following the guidelines at the top of the template.

**Comment by KirstieJane** [comment]
Thanks @stephwright! Here's our [budget template](https://docs.google.com/spreadsheets/d/1YZQTX9H5Y8IYlgYY-ifcG57uYt1xVxFtZ1Tc4oUfxpI/edit#gid=0). There doesn't seem to be any designated space for "a brief budget narrative". Should it just go inside the table? How is it different to the information in the application?

(This might not apply for salary by the way, which is what I'm asking about....)

**Comment by stephwright** [comment]
Ahhh... don't worry about the narrative.  This template is a generic Mozilla form that we co-opted for the mini-grants.  The application questions cover this.

**Comment by KirstieJane** [comment]
Hi @Islast! I'm off to sleep - I'll see you at 7am (3pm) for our meeting!

If you have time to take a look at what I've pulled together for the application form that would be super helpful. Any and all edits are very welcome. You can see that they're mostly just scrawled notes at the moment 😀 .

**Comment by KirstieJane** [comment]
This can be closed when PR #50 is merged :smile:
