### ISSUE TITLE
Change license from MIT to CC-BY

### ISSUE THREAD

**Issue by KirstieJane** [WhitakerLab/WhitakerLabProjectManagement#44]
Most of the information contained within this repository is documentation/curriculum resources rather than code so it makes more sense for us to use a CC-BY license rather than MIT.

The CC-BY license can be copied and pasted from here: https://choosealicense.com/licenses/cc-by-4.0/#

In order to complete the issue please first comment below to check that no one else is already working on the task. Then, once you're assigned: fork the repository, replace the text in the [LICENSE](https://github.com/WhitakerLab/WhitakerLabProjectManagement/blob/master/LICENSE) file with the CC-BY text above, then submit a pull request!

This issue has been labelled as a good first bug. That means it is a particularly good place for new/nervous github contibutors to get started :smile:

**Comment by stephwright** [comment]
If no one else has tackled this, I'm happy to do it!

**Comment by KirstieJane** [comment]
Go for it @stephwright!! 💯

**Comment by stephwright** [comment]
Back from lunch and gettin' on it now!

**Comment by stephwright** [comment]
PR submitted!

**Comment by KirstieJane** [comment]
Closed by PR #45! Thank you @stephwright :)
