### ISSUE TITLE
Add example attribution sentence to the README 

### ISSUE THREAD

**Issue by KirstieJane** [WhitakerLab/WhitakerLabProjectManagement#46]
There have been some great comments on twitter about the Whitaker Lab [CODE_OF_CONDUCT.md](https://github.com/WhitakerLab/WhitakerLabProjectManagement/blob/master/CODE_OF_CONDUCT.md) and requests to use the text for other groups/projects.

As part of the mozilla global sprint (\#mozsprint 🙌 ) @stephwright changed the [LICENSE](https://github.com/WhitakerLab/WhitakerLabProjectManagement/blob/master/LICENSE) from MIT to CC-BY (PR #44) which makes much more sense as almost everything in this repository is text rather than software.

The next step is to add a sample sentence to the [README](https://github.com/WhitakerLab/WhitakerLabProjectManagement/blob/master/README.md) file to make it super easy for anyone who does use materials from this repository to attribute the source :smile:.

If anyone wants to give this a whirl you're super welcome. Please comment on the issue to make sure that no one else is already working on it. Once you get the go ahead fork the repository and add an example sentence to the README in the [License and code of conduct](https://github.com/WhitakerLab/WhitakerLabProjectManagement/blob/master/README.md#license-and-code-of-conduct) section. Then submit a pull request and ask @KirstieJane to review 😀 .

**Comment by KirstieJane** [comment]
Oh......while we're at it, that section of the README says that the repo is licensed under MIT but it isn't anymore. So if you could fix that sentence while you're at it that would be amazing 💯

**Comment by daniellecrobinson** [comment]
I will work on this!

**Comment by KirstieJane** [comment]
Fantastic @daniellecrobinson!! Thank you 😀

**Comment by KirstieJane** [comment]
Closed by PR #47 YAAAAY!
