### ISSUE TITLE
Add links to papers in Network Neuroscience reading list

### ISSUE THREAD

**Issue by KirstieJane** [WhitakerLab/WhitakerLabProjectManagement#7]
The [Network Neuroscience](https://github.com/WhitakerLab/WhitakerLabProjectManagement/blob/master/READING_LISTS/NetworkNeuroscience.md) reading list has a great set of papers to get you started with Network Neuroscience.

It would be really helpful to link to the papers though rather than have to google them separately!

**Comment by dankessler** [comment]
I address this in #10 (and I did it before I noticed this issue!)

Thanks for sharing this reading list with the world :)

**Comment by KirstieJane** [comment]
Thanks @dankessler! I'm going to merge your PR tomorrow when my RA joins the group so I can talk her through it 😃 - way to be right on top of it!

**Comment by KirstieJane** [comment]
All done! Pull request #10 is merged 🎈 🎈 🎈
